### ISSUE TITLE
Doubts

### ISSUE THREAD

**Issue by yuregl** [MuhammadReda/nodejs-aws-lambda-image-resizer#1]
- Could I do all of this in a simple way by coding?
- Was it not clear to me, in relation to {s3_object_path}, he would have to be inside the production of the created bucket?
- or could it be anywhere in the bucket?
- Could {s3_object_path} be the object's url?

**Comment by MuhammadReda** [comment]
Hi Yure,

- Yes. You can build your own resizer using [these steps](https://github.com/MuhammadReda/nodejs-aws-lambda-image-resizer#build-your-own-aws-lambda-image-reiszer).
- That means if full image path is `https://{S3_BUCKET_NAME}.s3.us-east-2.amazonaws.com/level1/level2/image.png`, then `{s3_object_path}` is `level1/level2/image.png`.
- Yes. Image can be anywhere in the bucket.
- No. It has to be the relative path inside the bucket.

**Comment by yuregl** [comment]
Hi Muhammad,

- There is some flickering inside the code, I just tested everything worked fine, I sent it again with another resolution (nothing discrepant 1000x1000 and then with other sizes) and received the answer with {"message": "Internal Server Error"}. I followed the script that was created, is there anything else I should know?

**Comment by MuhammadReda** [comment]
Server errors should be logged in Cloudwatch. Take a look there and let me know.

**Comment by yuregl** [comment]
I checked and found the problem, there was little memory being used (in this case the standard), when I was going to do the resizing, I believe it burst and generated the error. I increased the size of the memory to be used and it worked with everyone else.

**Comment by Razorholt** [comment]
Hey @yuregl Where did you go to increase the memory? Thanks!

[EDIT}: Nevermind, found it!
https://docs.aws.amazon.com/lambda/latest/dg/configuration-memory.html

Thanks @MuhammadReda for this great tutorial!

**Comment by yuregl** [comment]
hey @MuhammadReda, the tutorial is great. I just wanted to know if you've used serverless to do this with yml. if yes did any tutorial explaining too?

**Comment by MuhammadReda** [comment]
@yuregl unfortunately not. But having to achieve that using Serverless is on my todo list.

**Comment by leelu-mary** [comment]
{"message":"Internal Server Error"} 
this the error that I, got while  followed exact same steps but i got this when i type my url

**Comment by MuhammadReda** [comment]
@leelu-mary make sure you have the correct node version set for your Lambda function
