### ISSUE TITLE
Sharp module have some error at the execution time

### ISSUE THREAD

**Issue by hackrx** [MuhammadReda/nodejs-aws-lambda-image-resizer#2]
When I am sending a get request, the execution is getting failed.
This is the output from CloudWatch:
```
START RequestId: <requestID> Version: $LATEST
2021-08-23T07:02:46.936Z	undefined	ERROR	
Something went wrong installing the "sharp" module

Cannot find module '../build/Release/sharp-linux-x64.node'
Require stack:
- /var/task/node_modules/sharp/lib/sharp.js
- /var/task/node_modules/sharp/lib/constructor.js
- /var/task/node_modules/sharp/lib/index.js
- /var/task/index.js
- /var/runtime/UserFunction.js
- /var/runtime/index.js

Possible solutions:
- Install with the --verbose flag and look for errors: "npm install --ignore-scripts=false --verbose sharp"
- Install for the current runtime: "npm install --platform=linux --arch=x64 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
END RequestId: <EndRequestID>
REPORT RequestId: <ReportRequestID>	Duration: 3110.80 ms	Billed Duration: 3000 ms	Memory Size: 128 MB	Max Memory Used: 22 MB	
2021-08-23T07:02:50.103Z <ID> Task timed out after 3.11 seconds

```

**Comment by hackrx** [comment]
I tried copying the code of the index.js and deployed the same as a zip file.
My package.json dependencies:
```
"dependencies": {
        "sharp": "^0.29.0"
    },
    "devDependencies": {
        "aws-sdk": "^2.36.0"
    }
```

**Comment by MuhammadReda** [comment]
@hackrx You can start by using [this latest build](https://github.com/MuhammadReda/nodejs-aws-lambda-image-resizer/releases/download/v1.5.37/build-1.5.37.zip) as your Lambda code, or choose one of the [stable builds](https://github.com/MuhammadReda/nodejs-aws-lambda-image-resizer/tags).

If the above worked, that means your AWS environment setup is fine.

To build your own version, you will need to follow the steps here [Build Your Own AWS Lambda Image Reiszer](https://github.com/MuhammadReda/nodejs-aws-lambda-image-resizer#build-your-own-aws-lambda-image-reiszer).

**Comment by hackrx** [comment]
Thanks @MuhammadReda for this code. Since I don't want to go with docker, I found a solution [here](https://stackoverflow.com/a/60217273/11902885). 
I hope it will also help others with the same issue.
