### ISSUE TITLE
File too large

### ISSUE THREAD

**Issue by manuelsechi** [MuhammadReda/nodejs-aws-lambda-image-resizer#5]
Hi,
just noticed the file you provided for download is bigger that 50MB and cannot be uploaded from the lambda console.

thanks
M

**Comment by MuhammadReda** [comment]
@manuelsechi you will need to upload the .zip file to Amazon S3, then will uploading Lambda code, choose `Amazon S3 location`

Detailed steps are here  [Lambda Function Setup](https://dynamic-aws-lambda-image-resizer-nodejs.mreda.net/03-aws-lambda-function-image-resizer-setup).
